# Generated by Django 5.2.1 on 2025-05-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Membresia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=15)),
                ('Membrecia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Membresia.membresia')),
            ],
        ),
    ]
