# Generated by Django 5.2.1 on 2025-05-19 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='Fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='Fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
