# Generated by Django 5.2.1 on 2025-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Clientes', '0002_miembro_fecha_final_miembro_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='Fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='Fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
