# Generated by Django 5.2.1 on 2025-05-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gestion_Productos", "0001_initial"),
        ("Gestion_Ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="Gestion_Productos.producto",
            ),
        ),
        migrations.RemoveField(
            model_name="detalleventa",
            name="precio_unitario",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
