# Generated by Django 5.2 on 2025-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Membresia', models.CharField(max_length=150)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
