# Generated by Django 5.2.1 on 2025-05-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Membresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='Duracion_dias',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
